using './orders-sb-containerapp.module.bicep'

param aca_env_outputs_azure_container_apps_environment_default_domain = '{{ .Env.ACA_ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param aca_env_outputs_azure_container_apps_environment_id = '{{ .Env.ACA_ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param aca_env_outputs_azure_container_registry_endpoint = '{{ .Env.ACA_ENV_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param aca_env_outputs_azure_container_registry_managed_identity_id = '{{ .Env.ACA_ENV_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param app_storage_outputs_blobendpoint = '{{ .Env.APP_STORAGE_BLOBENDPOINT }}'
param app_storage_outputs_queueendpoint = '{{ .Env.APP_STORAGE_QUEUEENDPOINT }}'
param cache_password_value = '{{ securedParameter "cache_password" }}'
param host_storage_outputs_blobendpoint = '{{ .Env.HOST_STORAGE_BLOBENDPOINT }}'
param host_storage_outputs_datalakeendpoint = '{{ .Env.HOST_STORAGE_DATALAKEENDPOINT }}'
param host_storage_outputs_queueendpoint = '{{ .Env.HOST_STORAGE_QUEUEENDPOINT }}'
param host_storage_outputs_tableendpoint = '{{ .Env.HOST_STORAGE_TABLEENDPOINT }}'
param messaging_outputs_servicebusendpoint = '{{ .Env.MESSAGING_SERVICEBUSENDPOINT }}'
param orders_sb_containerimage = '{{ .Image }}'
param orders_sb_identity_outputs_clientid = '{{ .Env.ORDERS_SB_IDENTITY_CLIENTID }}'
param orders_sb_identity_outputs_id = '{{ .Env.ORDERS_SB_IDENTITY_ID }}'
